// Generated by nitro
import type { Serialize, Simplify } from 'nitropack'
declare module 'nitropack' {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/cars': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/cars.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/cars.post').default>>>>
    }
    '/api/parts': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/parts.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/parts.post').default>>>>
    }
    '/api/sells': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/sells.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/sells.post').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nuxt/dist/core/runtime/nitro/renderer').default>>>>
    }
  }
}
export {}